resource_registry:
  OS::TripleO::ComputeSriov::PreNetworkConfig: /home/stack/templates/openstack-tripleo-heat-templates-new/extraconfig/pre_network/host_config_and_reboot.yaml

#parameter_defaults:
  # Note: There are no global parameters which can be applied to all roles as
  # these configuration have to be specific to role.

  # Sample parameters for Compute and ComputeOvsDpdk roles
  #ComputeParameters:
    #KernelArgs: ""
    #TunedProfileName: ""
    #IsolCpusList: ""
  ComputeOvsDpdkParameters:
    KernelArgs: "intel_iommu=on iommu=pt default_hugepagesz=1GB hugepagesz=1G hugepages=60"
    TunedProfileName: "cpu-partitioning"
    IsolCpusList: ""
