# This template configures each role to use a separate NIC for
# each isolated network.
# This template assumes use of network-isolation.yaml.
#
# FIXME: if/when we add functionality to heatclient to include heat
# environment files we should think about using it here to automatically
# include network-isolation.yaml.
resource_registry:
#  OS::TripleO::BlockStorage::Net::SoftwareConfig: /home/stack/templates1/nic-configs/cinder-storage.yaml
  OS::TripleO::Compute::Net::SoftwareConfig: /home/stack/templatesBIG/nic-configs/compute.yaml
#  OS::TripleO::Compute::Net::SoftwareConfig: /home/stack/templatesBIG/nic-configs/computeovsdpdksriov.yaml
  OS::TripleO::ComputeSriov::Net::SoftwareConfig: /home/stack/templatesBIG/nic-configs/computesriov.yaml
  OS::TripleO::Controller::Net::SoftwareConfig: /home/stack/templatesBIG/nic-configs/controller.hp.yaml
#  OS::TripleO::ObjectStorage::Net::SoftwareConfig: /home/stack/templates1/nic-configs/swift-storage.yaml
#  OS::TripleO::CephStorage::Net::SoftwareConfig: /home/stack/templates1/nic-configs/ceph-storage.yaml
  OS::TripleO::Services::NeutronSriovAgent: /usr/share/openstack-tripleo-heat-templates/docker/services/neutron-sriov-agent.yaml
  OS::TripleO::Services::NeutronSriovHostConfig: /usr/share/openstack-tripleo-heat-templates/puppet/services/neutron-sriov-host-config.yaml

parameter_defaults:
  NeutronDhcpAgentDnsmasqDnsServers: ['172.30.104.10','8.8.8.8']
  NetworkDeploymentActions: ['CREATE','UPDATE']
  InternalApiNetCidr: 10.130.198.30/24
  TenantNetCidr: 10.130.195.0/24
  StorageNetCidr: 10.130.197.30/24
  StorageMgmtNetCidr: 10.130.196.30/24
  ManagementNetCidr: 10.130.194.0/24
  ControlPlaneSubnetCidr: '26'
  ExternalNetCidr: 172.30.110.0/26
  InternalApiAllocationPools: [{'start': '10.130.198.30', 'end': '10.130.198.100'}]
  TenantAllocationPools: [{'start': '10.130.195.30', 'end': '10.130.195.100'}]
  StorageAllocationPools: [{'start': '10.130.197.30', 'end': '10.130.197.100'}]
  StorageMgmtAllocationPools: [{'start': '10.130.196.30', 'end': '10.130.196.100'}]
  ManagementAllocationPools: [{'start': '10.130.194.30', 'end': '10.130.194.100'}]
  # Leave room for floating IPs in the External allocation pool
  ExternalAllocationPools: [{'start': '172.30.110.20', 'end': '172.30.110.59'}]
  # Set to the router gateway on the external network
  ExternalInterfaceDefaultRoute: 172.30.110.62
  # Gateway router for the provisioning network (or Undercloud IP)
  ControlPlaneDefaultRoute: 172.30.110.126
  # The IP address of the EC2 metadata server. Generally the IP of the Undercloud
  EC2MetadataIp: 172.30.110.126
  # Define the DNS servers (maximum 2) for the overcloud nodes
  DnsServers: ["172.30.104.10"]
  InternalApiNetworkVlanID: 3198
  StorageNetworkVlanID: 3197
  StorageMgmtNetworkVlanID: 3196
  TenantNetworkVlanID: 3195
  ManagementNetworkVlanID: 3194
  ExternalNetworkVlanID: 130
  NeutronExternalNetworkBridge: "''"
  NeutronFlatNetworks: "sriov1,sriov2,dplane"
  NeutronBridgeMappings: "dplane:dataplane,sriov1:sriovp1p1,sriov2:sriovp1p2"
  NeutronNetworkVLANRanges: "dplane:100:3204,sriov1:3205:3208,sriov2:3205:3208"
  NeutronTunnelTypes: 'vxlan'
  NeutronNetworkType: 'flat,vlan,vxlan'
  NeutronVniRanges: '1:99'
  NeutronOVSFirewallDriver: openvswitch
# Nova flavor to use.
  OvercloudControllerFlavor: control
  OvercloudComputeSriovFlavor: compute
  OvercloudComputeFlavor: compute-small
  ControllerCount: 1
  ComputeSriovCount: 1
  ComputeCount: 4
#SRIOV
  NeutronMechanismDrivers: ['openvswitch','sriovnicswitch']
  NovaSchedulerDefaultFilters: ['RetryFilter','AvailabilityZoneFilter','RamFilter','ComputeFilter','ComputeCapabilitiesFilter','ImagePropertiesFilter','ServerGroupAntiAffinityFilter','ServerGroupAffinityFilter','PciPassthroughFilter','NUMATopologyFilter','AggregateInstanceExtraSpecsFilter']
  NovaSchedulerAvailableFilters: ["nova.scheduler.filters.all_filters","nova.scheduler.filters.pci_passthrough_filter.PciPassthroughFilter"]
  NeutronPhysicalDevMappings: ["sriov1:p1p1","sriov2:p1p2"]
  NovaPCIPassthrough:
    - devname: "p1p1"
      physical_network: "sriov1"
      trusted: "true"
    - devname: "p1p2"
      physical_network: "sriov2"
      trusted: "true"
  ComputeSriovParameters:
    TunedProfileName: "cpu-partitioning"
 #   OvsHwOffload: True
    NeutronSriovNumVFs: ["p1p1:8","p1p2:8"]
    IsolCpusList: 0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46
    KernelArgs: default_hugepagesz=1GB hugepagesz=1G hugepages=46 intel_iommu=on iommu=pt isolcpus=0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46
    NovaReservedHostMemory: 4096
    NovaVcpuPinSet: 0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46

