heat_template_version: pike
description: >
  Software Config to drive os-net-config to configure multiple interfaces for the compute role.
parameters:
  ControlPlaneIp:
    default: ''
    description: IP address/subnet on the ctlplane network
    type: string
  ExternalIpSubnet:
    default: '172.30.110.0/26'
    description: IP address/subnet on the external network
    type: string
  InternalApiIpSubnet:
    default: '10.130.198.40/24'
    description: IP address/subnet on the internal_api network
    type: string
  StorageIpSubnet:
    default: '10.130.197.40/24'
    description: IP address/subnet on the storage network
    type: string
  StorageMgmtIpSubnet:
    default: '10.130.196.40/24'
    description: IP address/subnet on the storage_mgmt network
    type: string
  TenantIpSubnet:
    default: '10.130.195.40/24'
    description: IP address/subnet on the tenant network
    type: string
  ManagementIpSubnet: # Only populated when including environments/network-management.yaml
    default: '10.130.194.40/24'
    description: IP address/subnet on the management network
    type: string
  ExternalNetworkVlanID:
    default: 130
    description: Vlan ID for the external network traffic.
    type: number
  InternalApiNetworkVlanID:
    default: 3198
    description: Vlan ID for the internal_api network traffic.
    type: number
  StorageNetworkVlanID:
    default: 3197
    description: Vlan ID for the storage network traffic.
    type: number
  StorageMgmtNetworkVlanID:
    default: 3196
    description: Vlan ID for the storage mgmt network traffic.
    type: number
  TenantNetworkVlanID:
    default: 3195
    description: Vlan ID for the tenant network traffic.
    type: number
  ManagementNetworkVlanID:
    default: 3194
    description: Vlan ID for the management network traffic.
    type: number
  ControlPlaneSubnetCidr: # Override this via parameter_defaults
    default: '26'
    description: The subnet CIDR of the control plane network.
    type: string
  ControlPlaneDefaultRoute: # Override this via parameter_defaults
    description: The default route of the control plane network.
    type: string
  ExternalInterfaceDefaultRoute: # Not used by default in this template
    default: unset
    description: The default route of the external network.
    type: string
  ManagementInterfaceDefaultRoute: # Commented out by default in this template
    default: unset
    description: The default route of the management network.
    type: string
  DnsServers: # Override this via parameter_defaults
    default: []
    description: A list of DNS servers (2 max for some implementations) that will be added to resolv.conf.
    type: comma_delimited_list
  EC2MetadataIp: # Override this via parameter_defaults
    description: The IP address of the EC2 metadata server.
    type: string
resources:
  OsNetConfigImpl:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config:
        str_replace:
          template:
            get_file: /home/stack/templates/openstack-tripleo-heat-templates-new/network/scripts/run-os-net-config.sh
          params:
            $network_config:
              network_config:
              - type: interface
                name: em1
                use_dhcp: true
                dns_servers:
                  get_param: DnsServers
                addresses:
                - ip_netmask:
                    list_join:
                    - /
                    - - get_param: ControlPlaneIp
                      - get_param: ControlPlaneSubnetCidr
                routes:
#                - ip_netmask: 169.254.169.254/32
#                  next_hop:
#                    get_param: EC2MetadataIp
                - default: true
                  next_hop:
                    get_param: ControlPlaneDefaultRoute
              - type: ovs_bridge
                name: dataplane
                dns_servers:
                  get_param: DnsServers
                members:
                - type: interface
                  name: em2
                  primary: true
                - type: vlan
                  vlan_id:
                    get_param: StorageNetworkVlanID
                  use_dhcp: false
                  addresses:
                  - ip_netmask:
                      get_param: StorageIpSubnet
                - type: vlan
                  vlan_id:
                    get_param: TenantNetworkVlanID
                  use_dhcp: true
                  addresses:
                  - ip_netmask:
                      get_param: TenantIpSubnet
                - type: vlan
                  vlan_id:
                    get_param: InternalApiNetworkVlanID
                  use_dhcp: false
                  addresses:
                  - ip_netmask:
                      get_param: InternalApiIpSubnet
              - type: ovs_bridge
                name: sriovp1p1
                dns_servers:
                  get_param: DnsServers
                members:
                - type: sriov_vf
                  device: p1p1
                  vfid: 3
              - type: ovs_bridge
                name: sriovp1p2
                dns_servers:
                  get_param: DnsServers
                members:
                - type: sriov_vf
                  device: p1p2
                  vfid: 3
              - type: interface
                name: p1p1
                mtu: 1500
                use_dhcp: false
                defroute: false
                nm_controlled: true
                hotplug: true
              - type: interface
                name: p1p2
                mtu: 1500
                use_dhcp: false
                defroute: false
                nm_controlled: true
                hotplug: true
#              - type: linux_bond
#                name: xl710_bond
#                bonding_options: mode=active-backup
#                use_dhcp: false
#                members:
#                - type: sriov_vf
#                  device: p1p1
#                  vfid: 1
#                - type: sriov_vf
#                  device: p1p2
#                  vfid: 1
#                bonding_options: "mode=802.3ad lacp_rate=[fast] updelay=1000 miimon=100"
              - type: sriov_pf
                name: p1p1
                numvfs: 8
              - type: sriov_pf
                name: p1p2
                numvfs: 8 
#                - type: vlan
#                  vlan_id:
#                    get_param: StorageMgmtNetworkVlanID
#                  use_dhcp: false
#                  addresses:
#                  - ip_netmask:
#                      get_param: StorageMgmtIpSubnet
#                - type: vlan
#                  vlan_id:
#                    get_param: ExternalNetworkVlanID
#                  use_dhcp: false
#                  addresses:
#                  - ip_netmask:
#                      get_param: ExternalIpSubnet
#                  routes:
#                  - default: true
#                    next_hop:
#                      get_param: ExternalInterfaceDefaultRoute
              # Uncomment when including environments/hyperconverged-ceph.yaml
              #- type: interface
              #  name: nic3
              #  use_dhcp: false
              #  addresses:
              #    - ip_netmask: {get_param: StorageMgmtIpSubnet}
            # Uncomment when including environments/network-management.yaml
            # If setting default route on the Management interface, comment
            # out the default route on the Control Plane.
            #- type: interface
            #  name: nic7
            #  use_dhcp: false
            #  addresses:
            #    - ip_netmask: {get_param: ManagementIpSubnet}
            #  routes:
            #    - default: true
            #      next_hop: {get_param: ManagementInterfaceDefaultRoute}
outputs:
  OS::stack_id:
    description: The OsNetConfigImpl resource.
    value:
      get_resource: OsNetConfigImpl

